# Working with Arrays

Sept 5, 2018

## numpy.empty

    numpy.empty(shape, dtype=float, order='C')
    Return a new array of given shape and type, without initializing entries.

Parameters:
    
    shape : int or tuple of int
        Shape of the empty array, e.g., (2, 3) or 2.

    dtype : data-type, optional
        Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.

    order : {‘C’, ‘F’}, optional, default: ‘C’
        Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

Returns: out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and order. Object arrays will be initialized to None.

See also
    empty_like
        Return an empty array with shape and type of input.
    ones
        Return a new array setting values to one.
    zeros
        Return a new array setting values to zero.
    full
        Return a new array of given shape filled with value.


## Ex1 - declare an array of m row and n columns (m x n ) aka matrix of mxn

In [1]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html
import numpy as np

row_size = 10
column_size = 8
meme = np.empty(shape=(row_size, column_size), dtype='int8')






## Ex 2 - examine the contents of array and properties of array

    shape, size, type, and ndim



In [2]:
meme

array([[  0,   0,   0,   0,   0,   0],
       [  0, -48,  69, -39, -35,  16],
       [ -5,   7,   0,  16,   4,   0],
       [  0,   0,   0,   0,   0, -48],
       [-49, -21, -35,  16,  -5,   7],
       [  0, -96,   3,   0,  93,  44],
       [ 32, 100, 116, 121, 112, 101],
       [ 61,  98, 111, 111, 108,  41],
       [  0, 116, 121, 112, 101,  61],
       [ 98, 111, 111, 108,  41,   0]], dtype=int8)

## Ex3 - declare an array with np.zeros

In [3]:
## put the code here - use a different variable like mem0
mem0 = np.zeros(shape=(row_size, column_size), dtype='int8')


In [4]:
mem0


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

## Ex4 - initialize the empty array with each cell assigned to its row index

In [5]:
for i in range(len(meme)):
    for j in range(len(meme[i])):
        mem0[i][j] = i
        
mem0

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9]], dtype=int8)

## Ex5 - take a slice or a view of empty array 'meme'

In [6]:
start_row = 2
end_row = 4
viewa = meme[start_row:end_row,:column_size]

viewa

array([[ -5,   7,   0,  16,   4,   0],
       [  0,   0,   0,   0,   0, -48]], dtype=int8)

## Ex6 - examine properties of viewa

 
## Ex7 - play with the slicing, extraction of view of array

## Ex8 - set the small array viewa to some number like '55'

In [7]:
rsize = viewa.shape[0]
csize = viewa.shape[1]
for r in range(rsize):
    for c in range(csize):
        viewa[r, c] = 55

In [8]:
viewa

array([[55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55]], dtype=int8)

## Ex9 - examine 'viewa' and 'meme'

## Ex10 - now set the contents of 'viewa' to a number like 355,
and examine the two arrays 'viewa' and 'meme'

In [9]:
for r in range(rsize):
    for c in range(csize):
        viewa[r, c] = 355
        

In [10]:
viewa

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]], dtype=int8)

# Class tutorial

In [11]:
class MyClass:
    aa = 44
    
    @classmethod
    def geta(cls):
        return MyClass.aa
    
    def geta1(self):
        return MyClass.aa
    
    @staticmethod
    def geta2():
        return MyClass.aa
    
    

In [12]:
MyClass.geta2()

44

In [13]:
a1 = MyClass()
a1

In [14]:
a1.geta1()

44